### ISSUE TITLE
[Enhancement] Button as a switch for boolean field

### ISSUE THREAD

**Issue by m-lotze** [dillingham/nova-button#10]
First of all this is an awesome package!

What i would like to see is an option to use it as a switch for a boolean field on the resource, e.g.:

```
Button::make('is_hidden')
            ->switch()
            ->trueLabel('text or html for an icon or similar')
            ->falseLabel('text or html for an icon or similar')
```

and in ButtonController maybe something like this:

```
public function handleSwitch(NovaRequest $request)
    {
        $resource = $request->findModelQuery()->firstOrFail();

        $resource->{$request->requestAttribute} = ! $resource->{$request->requestAttribute};

        if ($resource->save()) {
            return response($resource->{$request->requestAttribute}, 200);
        }

        return response('Something went wrong', 500);
    }
```

By sending back the new value the frontend than could change without reloading the whole page.

**Comment by dillingham** [comment]
Interesting idea! 

I can see switch or toggle being useful with this approach

Let me think on it though

**Comment by dillingham** [comment]
While definitely a cool idea, for now I think it's best to keep it as a traditional button.

It would clash with some things like style configs and such.

Thanks for proposing the idea though!
