### ISSUE TITLE
Exception: NovaButton\Providers\FieldServiceProvider not found

### ISSUE THREAD

**Issue by antonioribeiro** [dillingham/nova-button#11]
Not making much sense, because composer.json is referencing a file that's not present in the package tree:

![image](https://user-images.githubusercontent.com/3182864/51871053-78034180-233c-11e9-8e0d-a60be9e269cf.png)

**Comment by dillingham** [comment]
@antonioribeiro thanks, fixed & released

**Comment by antonioribeiro** [comment]
Nice, thank you!
