### ISSUE TITLE
Add Button::make()->attach('User') navigation

### ISSUE THREAD

**Issue by dillingham** [dillingham/nova-button#12]
It would be handy to add attach() like create and edit etc

**Comment by klepak** [comment]
I see you already have a branch going for this, but just thought I'd add this in case it is useful. 

I needed this functionality, so implemented a quick fix.

```
public function editAttached($namespace, $id, $relationNamespace, $relationId, $viaRelationship)
    {
        $this->route('edit-attached', [
            'resourceName' => $this->normalizeResourceName($namespace),
            'resourceId' => $id,
            'relatedResourceName' => $this->normalizeResourceName($relationNamespace),
            'relatedResourceId' => $relationId,
        ], [
            'viaRelationship' => $viaRelationship
        ]);

        return $this;
    }
```

```
Button::make('Text')->editAttached(
                    MainClass::class, $this->main_class_id,
                    RelationClass::class, $this->relation_class_id,
                    'relationMethod'
                )
```

```
public function route($name, $params, $query = [])
    {
        $this->type = 'route';

        $this->route = [
            'name' => $name,
            'params' => $params,
            'query' => $query,
        ];

        return $this;
    }
```

**Comment by dillingham** [comment]
@klepak ah thanks! Yeah I was trying to work it out so the resource the field was within was already associated and we only would declare the relation. But I also like the fact that your approach can be used anywhere.

**Comment by klepak** [comment]
@dillingham I think both approaches are valuable. In my case I wanted to add a link to edit the relationship between resource B and C from the details page of resource A. Depends on how customizable you need it I guess. Maybe try to auto-detect if no explicit parameters are provided?

**Comment by 4unkur** [comment]
Would be fine at least have a possibility to pass query string:  
```php
    public function route($name, $params, $query = [])
    {
        $this->type = 'route';

        $this->route = [
            'name' => $name,
            'params' => $params,
            'query' => $query,
        ];

        return $this;
    }
```

Currently it's impossible to pass query params...
