### ISSUE TITLE
Custom Fail Event Not Working in Event Listener 

### ISSUE THREAD

**Issue by joeelia** [dillingham/nova-button#14]
I have an API that I am calling when clicking the NovaButton and the Event Listener runs, but im making the API fail and the NovaButton still says the click action was successful. This is happening even when I use a try like this..

```
try {
               //Break the API here
      }catch (\Exception $e) {
                $this->failed($e);
               //The above is called and works as a fail, but the NovaButton doesn't show its 'failed' state
            }
```

**Comment by dillingham** [comment]
@joeelia you’re catching the exception. 

If the listener throws an exception, the button will indicate and display the error
