### ISSUE TITLE
Navigation to filter

### ISSUE THREAD

**Issue by ahmedkandel** [dillingham/nova-button#15]
Hi Brian,

As an enhancement to the navigation links routing to index with a filter may be as following:

In User resource a button to navigate to Order resource with UserOrders filter:

`Button::make($this->orders->count() . ' Orders')->index('App\Nova\Order')->filter('App\Nova\Filters\UserOrders', $this->id)`

then do json_encode and base64_encode to generate the filter URI.

Thanks

**Comment by dillingham** [comment]
Yeah I can see that being very useful, multiple filters too.. I'll look into it

```php
>filter([
    'App\Nova\Filters\UserOrders' => 1,
    'App\Nova\Filters\OrderStatus' => 'active',
])
```

Sidenote, on index, the ->count() will create a n+1 / eagerload problem

**Comment by ahmedkandel** [comment]
Will be perfect. Thanks, Brian for the sidenote.

**Comment by dillingham** [comment]
Will be included in an upcoming release, thanks @dkulyk !
