### ISSUE TITLE
can reload the selected field not reload whole page after event sucessed?

### ISSUE THREAD

**Issue by loveyuxiao** [dillingham/nova-button#19]
can reload the selected field not reload whole page after event sucessed?

**Comment by loveyuxiao** [comment]
just like nova action?

**Comment by SerjoA** [comment]
you can do this in the following way:
in your nova directory of nova src code, there is a component:
in nova/resources/js/views/index.vue

add this:

Nova.$on('customActionExecution', () => {
            this.getResources()
         })

to the end of created hook

then, in the NovaButton.vue file of this pkg, add this in the handle click method, there is a call to method
this.post()

add this when you get the response back or when ever you need:
Nova.$emit('customActionExecution');

**Comment by SerjoA** [comment]
remember, for doing this you need both nova button pkg to be compiled again, and nova src code to be compiled again

**Comment by dillingham** [comment]
Sorry that’s the only way I know how. 

Open to a PR that doesn’t override components
