### ISSUE TITLE
Button using icon [enhancement]

### ISSUE THREAD

**Issue by hubertnnn** [dillingham/nova-button#22]
Would be nice to add the ability to set the button to be an icon (similar to show, edit and delete buttons in nova)

I would imagine it to be configured like so:
`Button::make('Download')->icon('fa-download'),`

When using icon version it could use text as the buttons tooltip.

**Comment by dillingham** [comment]
@hubertnnn I managed to do an svg icon like so

```php
Button::make(view('icon.svg')->render(), 'download_button')
```

`icon.svg.blade.php`

The problem with fa-download is it assumes that fontawesome is installed
And Im not sure I want to add that overhead to this package

**Comment by hubertnnn** [comment]
Well, I was thinking more like keep the burden of installing the specific font to the user, and just allow creation of custom image icons. 

Since both glyphicons and font awesome (and probably other icon providers i never used before)
use similar format of `<span class="<provider> <provider>-<image>"`, allowing creation of icon button could just assume that whatever was in icon parameter is the class of that span.

That is the simplest solution that will cover most icon providers.
To go a step further you could add simple parsing for most commonly known formats eg.
- convert `glyphicon-XXX` to `glyphicon glyphicon-XXX`
- convert `fa-XXX` to `fa fa-XXX`
- if starts with `<svg` then use it as svg

**Comment by dillingham** [comment]
Button::make(‘<span class=“fa fa-download” />’, 'download')

**Comment by jobcerto** [comment]
Maybe this macro solves the problem? (Put in AppServiceProvider)
```php

   Button::macro('icon', function ($icon) {
            $this->text = sprintf('<i class="%s"></i>', $icon);

            return $this;
        });

  Button::make('Reports')->icon('fa fa-database');

```
