### ISSUE TITLE
Trying to figure out custom event listner

### ISSUE THREAD

**Issue by kevinab** [dillingham/nova-button#23]
I added to my event service provider:

`'\NovaButton\Events\ButtonClick' => [
            'App\Listeners\CloseFeedbackRequest',
        ]`

I have the following  listener:

`
namespace App\Listeners;

use \NovaButton\Events\ButtonClick;

class CloseFeedbackRequest
{

    /**
     * Create the event listener.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Handle the event.
     *
     * @param  ButtonClick  $event
     * @return void
     */
    public function handle(ButtonClick $event)
    {
        //
        if ($event->key == 'close-request') {
            $event->resource->closed_at = now();
            $event->resource->save();
        }
    }
}
`

And the following event:

`

namespace App\Events;

use Illuminate\Foundation\Events\Dispatchable;

class CloseFeedbackRequest
{
    use Dispatchable;

    public $resource;
    public $key;

    /**
     * Create a new event instance.
     *
     * @return void
     */
    public function __construct($resource, $key)
    {
        $this->$resource = $resource;
        $this->$key = $key;
    }

}
`
My button is 
`Button::make('Close', 'close-request')
                ->event('App\Events\CloseFeedbackRequest')
                ->visible($this->closed_at == null)
                ->confirm('Are you sure you want to close this request?')
                ->style('primary-outline'),`

My model is not getting updated what am I missing?

**Comment by dillingham** [comment]
$this->$resource = should be 
$this->resource =

**Comment by kevinab** [comment]
I corrected those and it still doesn't work. ... It doesn't look like the handler is getting called.

**Comment by dillingham** [comment]
Make sure you’ve registered the listener per the laravel docs

**Comment by kevinab** [comment]
is this not the correct way to register the listner?
`namespace App\Providers;

use Illuminate\Support\Facades\Event;
use Illuminate\Auth\Events\Registered;
use Illuminate\Auth\Listeners\SendEmailVerificationNotification;
use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;

class EventServiceProvider extends ServiceProvider
{
    /**
     * The event listener mappings for the application.
     *
     * @var array
     */
    protected $listen = [
        Registered::class => [
            SendEmailVerificationNotification::class,
        ],
        '\NovaButton\Events\ButtonClick' => [
            'App\Listeners\CloseFeedbackRequest',
        ]
    ];

    /**
     * Register any events for your application.
     *
     * @return void
     */
    public function boot()
    {
        parent::boot();

        //
    }
}`

**Comment by dillingham** [comment]
CloseFeedbackRequest Is your event
ButtonClick is your registered event. 

Good luck! :)

**Comment by kevinab** [comment]
Just trying to follow the example in your documentation but your documentation does not include the registration of the eventlistener ... that would be helpful to add.

**Comment by dillingham** [comment]
I linked to the docs on how to do it. 
https://laravel.com/docs/5.7/events

You’re welcome!!
