### ISSUE TITLE
How to pass parameter when confirm the execution?

### ISSUE THREAD

**Issue by phoenixg** [dillingham/nova-button#26]
For example, I want to pass the `date`.

**Comment by dillingham** [comment]
Do it in your listener

**Comment by phoenixg** [comment]
@dillingham Listener can catch the `event`'s parameter, but it cannot change it to other value.

**Comment by dillingham** [comment]
It’s the model, update it. Good luck 👍

**Comment by phoenixg** [comment]
Hmmmmm, but I actually want an input box to manually change it on the web interface.

**Comment by SerjoA** [comment]
its not possible at the moment

**Comment by phoenixg** [comment]
@SerjoA Is it possible in the future?

**Comment by SerjoA** [comment]
iam not one of the mainteners
i am working on it also for my self but for the moment i dont know how much time it will take

**Comment by SerjoA** [comment]
i thought about an api like this:
Button::make('Deposit')
     ->action(DepositAction::class)
     ->canSee(.....),

i think it will be better than say:
Button::make('Deposit')
     ->fields([
         Text::make('Amount'),
      ])
     ->canSee(.....),

in terms of reusability and etc
if and when ill finish ill submit pr

**Comment by dillingham** [comment]
I don’t want to add resolving fields to this package. I did it in another package of mine and it’s been a headache.  I would merge in ->action() if it somehow relied on novas native handling of all that stuff. Ui / controller etc.

**Comment by SerjoA** [comment]
ok, if i succeed with that i will submit pr
thanks for the package

**Comment by dillingham** [comment]
@phoenixg I didn’t understand your question originally. Here is a related thread https://github.com/dillingham/nova-button/issues/18

**Comment by dillingham** [comment]
@SerjoA awesome, feel free to ask questions of brainstorm on that thread and I’ll try to help as much as I can

**Comment by phoenixg** [comment]
@SerjoA Looking forward to
