### ISSUE TITLE
is there a way to trigger action with fields? or just action?

### ISSUE THREAD

**Issue by SerjoA** [dillingham/nova-button#27]

**Comment by dillingham** [comment]
the button can trigger events, those events  can have listeners, those listeners can share the same code  your Nova actions are using. But currently there is not a way to run an action. Will add it eventually.

**Comment by SerjoA** [comment]
first thanks for quick response, love the package
i would like to help you
you can point me to a reference on how to add an action fields to the button or re use an action class already made by me for example,
i saw your source code but i could not figure out on how to do that , or exactly, where to put changes 
i saw you have a title and the body for the confirmation and i saw the vue code but couldnt quite figure out , i think the best course of action is to reuse the action classes and get theire data,  like fields, insted of something else

**Comment by dillingham** [comment]
https://github.com/dillingham/nova-button/issues/18
