### ISSUE TITLE
Possible to stack/combine "event" and "index" methods

### ISSUE THREAD

**Issue by asilverstein** [dillingham/nova-button#28]
I would like to do this:
```
Button::make('Run')
                ->event('App\Events\ApplyFiltersEvent')
                ->index('App\Nova\User'),
```
Basically, navigate to the User index page **after** firing the event. It seems to be either-or in the current code. Perhaps there is another way?

Thanks.

**Comment by dillingham** [comment]
I’ll look into doing this
