### ISSUE TITLE
Button::make('Text')->index('App\Nova\User') with viaResourceId,viaRelationship,relationshipType,viaResource

### ISSUE THREAD

**Issue by loveyuxiao** [dillingham/nova-button#30]
can do this?
Button::make('Text')->index('App\Nova\User',
"viaResourceId" => $model->id,
 "viaRelationship" => "Product",
"relationshipType" => "hasMany",
"viaResource" => "product-resources",
])

**Comment by dillingham** [comment]
Added in [1.0.6](https://github.com/dillingham/nova-button/releases/tag/1.0.6)
