### ISSUE TITLE
Feature: Allow fire of action on resource

### ISSUE THREAD

**Issue by otrsw** [dillingham/nova-button#32]
Great component!  Adding lots of value to my nova apps.

Just thought I would request a possible feature/enhancement - it would be great if I could trigger an action from the button for the selected resource.  
So something like:

    Button::make('Text')->action('App\Nova\Actions\SendUserMessage', $this->user_id)

It would allow the collection of fields via the normal Action workflow - so essentially a shortcut for selecting the resource and running the action from the Actions dropdown.

**Comment by loveyuxiao** [comment]
i need this function too

**Comment by PrafullaKumarSahu** [comment]
@otrsw Any update on this?

**Comment by otrsw** [comment]
Hi @PrafullaKumarSahu - nope no feedback yet from @dillingham

**Comment by dillingham** [comment]
Duplicate https://github.com/dillingham/nova-button/issues/18
