### ISSUE TITLE
Let button post a form with hidden fields

### ISSUE THREAD

**Issue by MartinMorlog** [dillingham/nova-button#33]
I need a button that submits a form with some hidden fields.

```html
<form action="example.org/login" target="_blank" method="post">
    <input type="hidden" name="username" value="my_name">
    <input type="hidden" name="password" value="12345678">
</form>
```
It might use the resource to fill the fields:

```php
Button::make('Login')
    ->link('example.org/login', '_blank', 'POST')
    ->addHiddenField('username')
    ->addHiddenField('password', 'external_password')
    ->addHiddenField('one_more_field', function () {
        return $this->resource->someMethod();
    }),
```
Is this something you would consider adding to your package?

**Comment by dillingham** [comment]
Hey! Sorry but if you want  access to the resource when t he  button is  clicked.. you already have  it in the event / listener scenario. Not adding fields to  the button.. sorry.
