### ISSUE TITLE
Feature Request: Actions Drop-down

### ISSUE THREAD

**Issue by nikhilbaby2000** [dillingham/nova-button#35]
A drop down action list would be nice to have.
To get an basic idea on the list: 

![image](https://user-images.githubusercontent.com/9396751/61806919-3b7d5200-ae56-11e9-842a-22db23e1b061.png)

PS: Please ignore the options in the image. My requirement was to add actions like:
> Login As
> Confirm Email
> Resend Confirmation
> Refund

Thanks. Great package :+1:

**Comment by dillingham** [comment]
Thanks! I feel like that is out of the scope of this package
