### ISSUE TITLE
Run Nova action on button click

### ISSUE THREAD

**Issue by hsharghi** [dillingham/nova-button#36]
NovaButton can be a very nice shortcut way to use Nova actions. Instead of selecting a row and selecting an action from the drop-down menu, just click on a NovaButton. So is it possible to run a pre-defined action by clicking a NovaButton?

**Comment by dillingham** [comment]
duplicate https://github.com/dillingham/nova-button/issues/18

I agree but just dont want to flood the markup with a bunch of form fields for each row
