### ISSUE TITLE
Modal css on Responsive Theme

### ISSUE THREAD

**Issue by noxahti** [dillingham/nova-button#39]
I installed nova-button as well as the ResponsiveTheme package. But I'm having problem with the css of the **modal**. Locally I changed the components IndexField.vue and DetailField.vue to add manually the **width: 100% !important** (and also added some margin top), as I saw in the css file of the ResponsiveTheme, and it worked perfectly.

But, obviously, when I deploy my app, it will be installed from nova-button git and not get my changes.

Should I do some config to reflect the Responsive css to the modal? Or is it an issue with nova-button package?

![image](https://user-images.githubusercontent.com/47398037/63563702-68e21c00-c538-11e9-9c42-6708f9ff8f52.png)

**Comment by dillingham** [comment]
@noxahti added a fix in 1.0.7.

**Comment by dillingham** [comment]
For future reference: you can use `php artisan nova:theme` to add your own customizations without touching nova components
