### ISSUE TITLE
Feature Request: Trigger Nova Action with Resource

### ISSUE THREAD

**Issue by calebcook** [dillingham/nova-button#40]
Hey! Great package - fits really well into my Nova client interface.

Would love to have a way to have the button trigger a Nova Action and pass the resource through to that Action (so it would be the same as if I selected the single resource checkbox, and picked an Action from the select box.)
<img width="783" alt="Screen Shot 2019-08-26 at 9 35 41 PM" src="https://user-images.githubusercontent.com/5931635/63734323-d0a2aa80-c849-11e9-9f61-b55f8d953b87.png">

With Nova Actions, I'm able to create a pop-up with extra custom fields that I can populate before initiating the Action. 
<img width="775" alt="Screen Shot 2019-08-26 at 9 39 11 PM" src="https://user-images.githubusercontent.com/5931635/63734368-f8920e00-c849-11e9-8414-7aae32d62820.png">

Being able to initiate this popup (or any Nova Action) with just a button rather than the 3-step process would be very helpful. (something like `Button::make('Text')->action('App\Nova\Actions\SendText')`)

**Comment by dillingham** [comment]
Nova now has action selects per row
https://nova.laravel.com/docs/2.0/actions/defining-actions.html#overview
`->showOnTableRow()`
