### ISSUE TITLE
Button not showing on index with nova-mega-filter in use

### ISSUE THREAD

**Issue by bernhardh** [dillingham/nova-button#53]
If someone is using the https://novapackages.com/packages/digital-creative/nova-mega-filter package, the button will not show up on index pages, since it has no value for the attribute property.

To fix it, you just can set it:

```
$btn = Button::make("Preview")
    ->showOnIndex();
$btn->attribute = "preview";
```

It would be great, if we could set it by a `setAttributeName` method or even as second `make` parameter, so that we can use method chaning and don't have to directly manipulate object properties.

**Comment by dillingham** [comment]
In retrospect I shouldn't have made the second param of `make` the ajax id
Maybe I should correct that on a major release
