### ISSUE TITLE
How to make a toogle button with visual change

### ISSUE THREAD

**Issue by didix16** [dillingham/nova-button#57]
Hello,
First of all thanks for make this project to allow make new buttons to table rows :).

I want to add a "favorite button" with star icon such that when I click on it, marks the resource as favorite in resource favorite relation and visually, the icon must change to represent that is marked as favorite. Also if I click again on favorite icon, It should unmark favorite relation and show initial state button.

I've been looking at the docs but I can't figure out how to do it.

Could someone put an example of how can I make a toggle event that changes the svg icon ( on success ) and call the programed action ?

Thank you in advance!

**Comment by dillingham** [comment]
You can use two buttons and `->visible($this->is_favorited)`
You can also store svg icons and render as first param I believe
And maybe `->reload()` to show the other button automatically
Or `->successText($icon)` to avoid the reload maybe.

Haven't tried this, just speculating. Hope this helps!

```php
$favoriteSvg = view()->make('svg.favorite')->render();

Button::make($favoriteSvg, 'favorite_toggle')
    ->visible($this->is_favorited)
    ->reload(),
```

Then you'd make a event / listener that attaches / detaches favorites

**Comment by didix16** [comment]
Thanks @dillingham. I'll try :+1:

**Comment by didix16** [comment]
Seems like it works but when successText is rendered , the new button has not a registered event, so I can't trigger again the toggle event.

I don't want to use reload because I want to toggle some of them at the same time.

Is there any chance to register again the event when successText is called?

Thanks in advance

**Comment by dillingham** [comment]
No not currently. That would require a new feature. Something like a toggle method with two passed events to switch between. I’m open to a PR but don’t have time to do that myself. You’re other option is to fork this or use it as inspiration for your own custom field. Good luck!

**Comment by didix16** [comment]
Thanks @dillingham for the info!
I'll see what I'll do.
