### ISSUE TITLE
Retain table cells for non-visible buttons

### ISSUE THREAD

**Issue by flxsource** [dillingham/nova-button#6]
If you set a visibility condition on a button, if there are any rows where no button matches (and, I assume, differing numbers of buttons) the columns become misaligned (See screenshot). Would it be better for non-visible buttons to product an empty cell rather than nothing at all?

![image](https://user-images.githubusercontent.com/1785446/51149561-8b051480-185a-11e9-9901-456710d089ff.png)

Currently the workaround is to add additional button with an empty label with a visibility condition that is complimentary.

**Comment by dillingham** [comment]
@flxsource thanks, I'll be releasing a fix for this soon that will include an empty cell for index
