### ISSUE TITLE
Create link in resource table row

### ISSUE THREAD

**Issue by Paulsky** [dillingham/nova-button#67]
Thank you for this package!

The only thing I want to accomplish, is a link in my resource table, which looks exactly the same as the other actions (I really don't understand why this is so hard to do in Nova https://github.com/laravel/nova-issues/issues/786). I don't need callbacks, success messages, error messages or loading messages. Just a link that has the same design and size as the other default actions. Could you please help me out?

```
Button::make('Just a link')
            ->style('primary')
            ->loadingStyle('primary')
            ->successStyle('primary')
            ->loadingText('Just a link')
            ->successText('Just a link')
            ->link('/my-custom-route/myCustomId', '_self')
            ->onlyOnIndex();
```

![just-a-link](https://user-images.githubusercontent.com/9481318/82728233-70b13580-9cef-11ea-92cb-0a84053376e7.PNG)

**Comment by camaech** [comment]
`Button::make($this->project->company->name)->detail('App\Nova\Company', $this->project->company->id),`

**Comment by dillingham** [comment]
There is a "link" style. "Primary" looks like a button.
