### ISSUE TITLE
Add parameter to event

### ISSUE THREAD

**Issue by ardit-okshtuni-atis** [dillingham/nova-button#8]
Hi, can i add parameter to custom event that i call for example: $this->id
so in listener i can access that resource and modify or do my actions? 
Thanks a lot :) awesome package

My code

Button::make('Activate')
->event('App\Events\ActivateUser', $this->id)
->visible($this->status == 0)
->confirm('Are you sure?')
->style('success-outline'),

Button::make('Deactivate')
->event(new DeactivateUser($this->id))
->visible($this->status == 1)
->confirm('Are you sure?')
->style('danger-outline'),

**Comment by dillingham** [comment]
@ardit-okshtuni-atis Hey thanks, and for the idea.

Currently that event will receive $resource $key
So in your `DeactivateUser($resource, $key)`
You can access the user id like so `$this->resource->id`

Check out this example https://github.com/dillingham/nova-button#example

**Comment by dillingham** [comment]
The events are triggered via ajax. 
So passing parameters isn't an option currently
